<a href="https://colab.research.google.com/github/Anushka29-code/ML117/blob/main/session2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
my_list=[1,2,3]
my_list

[1, 2, 3]

In [8]:
np.array(my_list)

array([1, 2, 3])

In [9]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [19]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(2)

array([0.23295279, 0.81448098])

In [22]:
np.random.rand(5,5)

array([[0.19685806, 0.14867338, 0.31937176, 0.87107865, 0.15687817],
       [0.47448924, 0.35661951, 0.6643975 , 0.98845443, 0.56565408],
       [0.74777052, 0.43471622, 0.10670977, 0.66362738, 0.45795951],
       [0.25534902, 0.26489808, 0.68048093, 0.03213944, 0.06022265],
       [0.25869346, 0.84912535, 0.96837556, 0.14882139, 0.46201722]])

In [23]:
np.random.randn(2)

array([ 1.72139033, -1.14186805])

In [24]:
np.random.randn(5,5)

array([[-2.23024972, -0.85173201,  0.08168097,  0.0346975 ,  1.45193735],
       [ 0.58205078,  0.0926064 , -1.37491349, -1.05846279, -0.76666157],
       [-1.11640345, -1.66131832,  0.76957099,  0.69132079, -0.04635145],
       [-0.6282653 ,  0.83275039, -0.95347409, -0.9972336 , -1.37176779],
       [-0.03621371,  1.80374976,  0.78058295, -0.68628845, -0.53490635]])

In [25]:
np.random.randint(1,100)

94

In [26]:
np.random.randint(1,100,10)

array([75, 34, 48, 73, 90, 25,  2, 84, 19, 39])

In [28]:
arr=np.arange(25)
ranarr=np.random.randint(0,50,10)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr

array([25, 26, 49, 20,  8,  8, 44,  5, 11, 28])

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr

array([25, 26, 49, 20,  8,  8, 44,  5, 11, 28])

In [35]:
ranarr.max()

np.int64(49)

In [36]:
ranarr.argmax()

np.int64(2)

In [38]:
ranarr.min()

np.int64(5)

In [39]:
ranarr.argmin()

np.int64(7)

In [40]:
#vector
arr.shape

(25,)

In [41]:
#notice the two sets of bracket
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [42]:
arr.reshape(1,25).shape

(1, 25)

In [43]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [45]:
arr.reshape(25,1).shape

(25, 1)

In [46]:
arr.dtype

dtype('int64')